[package]
name = "rust-operator"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
futures-util = "0.3.31"
k8s-openapi = { version = "0.26.0", features = ["latest"]}
kube = { version = "2.0.1", features = ["runtime", "derive"]}
schemars = "1.0.4"
serde = { version = "1.0.228", features = ["derive"]}
serde_json = "1.0.145"
serde_yaml = "0.9.34"
sha2 = "0.10.9"
tokio = { version = "1.48.0", features = ["rt-multi-thread", "macros"]}
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["fmt", "env-filter"]}
