
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base


patches:
  - target:
      kind: Deployment
      name: rust-operator
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: rust-operator
      spec:
        template:
          spec:
            containers:
            - name: controller
              imagePullPolicy: Never
